/**
 * @atomic-fi/sdk — typed client for the AtomicFi API.
 *
 * Generated artifacts under `generated/` come from `spec/openapi.yaml` (which
 * itself is generated by `mix openapi.spec.yaml` against `AtomicFiApi.ApiSpec`).
 *
 *   import { client, ... } from '@atomic-fi/sdk'
 *
 * For typed request/response shapes:
 *
 *   import type { ... } from '@atomic-fi/sdk/types'
 */
export * from '../generated/sdk.gen.ts'
export { client } from '../generated/client.gen.ts'
export type * from '../generated/types.gen.ts'
