import Config

# System entities for seeding (platform pattern — nested per-resource config)
config :atomic_fi, :system_tenant,
  name: "atomic-fi-tenant",
  slug: "atomic-fi-tenant"

config :atomic_fi, :admin_user,
  email: "admin@atomic-fi.local",
  password: "admin-password-dev"

config :atomic_fi, :bot_user, email: "bot@atomic-fi.local"

config :atomic_fi, :root_api_key, "alvera_root_api_key_dev"

# Configure encryption vault
config :atomic_fi, AtomicFi.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1", key: Base.decode64!("3nGslycHroShfsRKvmMSsURKZrJuK6euXTKkMYfD8+8=")}
  ]

# Configure your database
config :atomic_fi, AtomicFi.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "atomic_fi_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :atomic_fi, AtomicFiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4100],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "9FVHZ5vPQIMeW6X++NhBtMOxA+wKiNB+kA33WrDThi7NBURRkhbpOjHH7U1p3G+v",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :atomic_fi, AtomicFiWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/atomic_fi_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :atomic_fi, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# OpenAPI Generator configuration for Watchman client (dev-only dependency)
config :oapi_generator,
  watchman: [
    output: [
      base_module: AtomicFi.Watchman,
      location: "lib/atomic_fi/watchman"
    ]
  ]

# LotusRepo — same DB, no RLS enforcement (Lotus needs unscoped schema access)
config :atomic_fi, AtomicFi.LotusRepo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "atomic_fi_dev",
  pool_size: 5

# Import OpenAPI server configuration
import_config "openapi_servers.#{config_env()}.exs"

# Import dev secrets (API keys, etc.) — not checked into version control.
# Copy config/dev.secret.exs.example to config/dev.secret.exs and fill in values.
if File.exists?(Path.expand("dev.secret.exs", __DIR__)) do
  import_config "dev.secret.exs"
end
