defmodule AtomicFi.Repo.Migrations.AddExternalIdToBeneficialOwners do
  use Ecto.Migration

  # Adds `external_id` to `beneficial_owners`, mirroring the AH/CP/PA
  # convention: a caller-supplied SoE handle that's unique per tenant
  # (Stripe/JPMC/Moov upstream ids; corpus.validate fixture handles
  # like `bo-acme-ubo-01`).
  #
  # Until this migration, BO had only the autogenerated
  # `beneficial_owner_number` for internal identification, which made
  # corpus.validate (and any external caller) unable to idempotently
  # look up a specific BO by a stable handle — `external_id` closes
  # that gap so the BO ndjson loader can match the AH/CP/PA loader
  # shape exactly.
  #
  # Partial unique index: scoped per tenant; nullable column so the
  # field stays optional (matches AH/CP/PA — only the corpus + SoE
  # integrations need a handle; in-app BO creates can stay nameless).

  def change do
    alter table(:beneficial_owners) do
      add :external_id, :string,
        comment: "Caller-supplied SoE handle (e.g. corpus fixture key). Unique per tenant."
    end

    create unique_index(:beneficial_owners, [:external_id, :tenant_id],
             where: "external_id IS NOT NULL",
             name: :beneficial_owners_external_id_tenant_id_unique
           )
  end
end
